format = "$env_var$username$hostname$directory$git_branch$git_commit$git_state$git_status$package$dotnet$nodejs$rust$custom$cmd_duration$line_break$jobs$battery$time$status$character"

[character]
success_symbol = "[➜](bold fg:#a3be8c) "
error_symbol = "[✗](bold fg:#bf616a) "

[cmd_duration]
style = "fg:#ebcb8e"

[directory]
style = "bold fg:#81a1c1"

[git_branch]
style = "bold fg:#b48ead"

[git_state]
style = "bold fg:#ebcb8b"

[git_status]
style = "bold fg:#bf616a"

[hostname]
ssh_only = false
style = "bold fg:#5e81ac"

[env_var]
variable = "OS_GLYPH"
default = ""
style = "bold white"
format = '[$env_value]($style) '
