format = '┌$username $hostname $git_branch $git_commit$git_state$git_status$package$dotnet$nodejs$rust$custom$line_break└$status\[$directory\] $character'
command_timeout = 1000

[character]
success_symbol = '[](bold fg:#a3be8c)'
error_symbol = '[](bold fg:#bf616a)'
vicmd_symbol = '[](bold fg:#eceff4)'

[cmd_duration]
style = 'fg:#ebcb8e'

[directory]
style = 'bold fg:#81a1c1'
format = '[  $path]($style)[$read_only]($read_only_style)'
read_only = ''

[git_branch]
style = 'bold fg:#b48ead'
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 6
format = '[\( $hash$tag\)]($style) '
style = 'bold green'
only_detached = true

[git_state]
style = 'fg:#ebcb8b'
format = '\([$state($progress_current/$progress_total)]($style)\)'

[git_status]
style = 'bold fg:#bf616a'
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
ssh_only = false
style = 'bold fg:#5e81ac'
format = '[ $hostname]($style)'

[package]
style = 'bold fg:#e5e9f0'
symbol = '  '
format = '[$symbol$version]($style) '
version_format = '$raw'

[rust]
style = 'bold fg:#d08770'
symbol = ' '
format = '[$symbol($version )]($style)'

[username]
show_always = true
style_root = 'bold fg:#bf616a'
format = '[  $user]($style)'
